// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg337APfTSwq_AVacVWfXPdgf4Ted-nmY',
    appId: '1:799598011210:web:4b1fc599fcb24378e617b3',
    messagingSenderId: '799598011210',
    projectId: 'flutterfire-ui-codelab-1ad67',
    authDomain: 'flutterfire-ui-codelab-1ad67.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-1ad67.appspot.com',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADBT9Hg-T3jN0pQk3Vlg8duGogUymQQwE',
    appId: '1:799598011210:android:b171b4d18d8bd6ede617b3',
    messagingSenderId: '799598011210',
    projectId: 'flutterfire-ui-codelab-1ad67',
    storageBucket: 'flutterfire-ui-codelab-1ad67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTED7GmtKxom8tzP2b3XAJJ5ez3Pjk_ZE',
    appId: '1:799598011210:ios:ae419c197ce67c9de617b3',
    messagingSenderId: '799598011210',
    projectId: 'flutterfire-ui-codelab-1ad67',
    storageBucket: 'flutterfire-ui-codelab-1ad67.appspot.com',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTED7GmtKxom8tzP2b3XAJJ5ez3Pjk_ZE',
    appId: '1:799598011210:ios:ae419c197ce67c9de617b3',
    messagingSenderId: '799598011210',
    projectId: 'flutterfire-ui-codelab-1ad67',
    storageBucket: 'flutterfire-ui-codelab-1ad67.appspot.com',
    iosBundleId: 'com.example.start',
  );

}